//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="StudentsData")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="StudentsData", IsNullable=false)]
public partial class Students {
    
    private StudentsStudent[] studentField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Student")]
    public StudentsStudent[] Student {
        get {
            return this.studentField;
        }
        set {
            this.studentField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="StudentsData")]
public partial class StudentsStudent {
    
    private string nameField;
    
    private string surnameField;
    
    private System.DateTime date_of_birthField;
    
    private StudentsStudentAdress_pernam adress_pernamField;
    
    private StudentsStudentAdress_temp adress_tempField;
    
    private StudentsStudentClass[] classesField;
    
    /// <remarks/>
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    public string Surname {
        get {
            return this.surnameField;
        }
        set {
            this.surnameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime Date_of_birth {
        get {
            return this.date_of_birthField;
        }
        set {
            this.date_of_birthField = value;
        }
    }
    
    /// <remarks/>
    public StudentsStudentAdress_pernam Adress_pernam {
        get {
            return this.adress_pernamField;
        }
        set {
            this.adress_pernamField = value;
        }
    }
    
    /// <remarks/>
    public StudentsStudentAdress_temp Adress_temp {
        get {
            return this.adress_tempField;
        }
        set {
            this.adress_tempField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Class", IsNullable=false)]
    public StudentsStudentClass[] Classes {
        get {
            return this.classesField;
        }
        set {
            this.classesField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="StudentsData")]
public partial class StudentsStudentAdress_pernam {
    
    private string cityField;
    
    private string streetField;
    
    /// <remarks/>
    public string City {
        get {
            return this.cityField;
        }
        set {
            this.cityField = value;
        }
    }
    
    /// <remarks/>
    public string Street {
        get {
            return this.streetField;
        }
        set {
            this.streetField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="StudentsData")]
public partial class StudentsStudentAdress_temp {
    
    private string cityField;
    
    private string streetField;
    
    /// <remarks/>
    public string City {
        get {
            return this.cityField;
        }
        set {
            this.cityField = value;
        }
    }
    
    /// <remarks/>
    public string Street {
        get {
            return this.streetField;
        }
        set {
            this.streetField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="StudentsData")]
public partial class StudentsStudentClass {
    
    private string nameField;
    
    private byte gradeField;
    
    /// <remarks/>
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    public byte Grade {
        get {
            return this.gradeField;
        }
        set {
            this.gradeField = value;
        }
    }
}
